[workspace]
resolver = "2"
members = [
    "crates/masterbus",
    "crates/masterbus-ffi",
    "crates/masterbus-tools",
]

[workspace.package]
version = "0.3.4"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/keesverruijt/masterbus"

[workspace.dependencies]
thiserror = "2"
crossbeam-channel = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
socketcan = "3"
ratatui = "0.30"
log = "0.4"
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }
masterbus = { path = "crates/masterbus", version = "0.3.4" }
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }

[profile.release]
opt-level = "z"
lto = true
